# Generated by Django 2.0.6 on 2020-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='产品列表',
            options={'ordering': ('-价格',), 'verbose_name_plural': '产品列表'},
        ),
        migrations.AddField(
            model_name='产品列表',
            name='购买地址',
            field=models.TextField(blank=True),
        ),
    ]
